controllers/AdminController.php
<?php

namespace app\controllers;

use app\models\Check;
use app\models\Checklog;
use app\models\Url;
use app\models\UrlSearch;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;


class AdminController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'access' => [
                    'class' => AccessControl::className(),
                    'rules' => [
                        [
                            'actions' => ['checklog', 'view', 'index'],
                            'allow' => true,
                            'roles' => ['@'],
                        ],
                    ],
                ],
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Url models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new UrlSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     *
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $query = Check::find()->where(['url_id' => $model->id]);
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 20,
            ],
            'sort' => [
                'defaultOrder' => [
                    'created_at' => SORT_DESC,
                ]
            ],
        ]);
        return $this->render('view', [
            'model' => $dataProvider,
        ]);
    }
    public function actionChecklog($id)
    {
        $check = Check::findOne($id);
        $query = Checklog::find()->where(['check_id' => $check->id]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 20,
            ],
            'sort' => [
                'defaultOrder' => [
                    'created_at' => SORT_DESC,
                ]
            ],
        ]);
        foreach ($dataProvider->getModels() as &$model) {
           $model->url_string     =  $model->getUrl()->asArray()->one()['url'];

        }
        return $this->render('checklog', [
            'model' => $dataProvider,
        ]);
    }


    /**
     * Finds the Url model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Url the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Url::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(\Yii::t('app', 'The requested page does not exist.'));
    }
}

views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>

    <?php /*

    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <?php if(Yii::$app->user->isGuest): ?>
                    <li class="nav-item">
                        <a class="nav-link" href=<?= \yii\helpers\Url::to(" /user/security/login") ?>>Sign In</a>
                    </li>

                <?php else: ?>
                    <li class="nav-item active">
                        <a class="nav-link" href=<?= \yii\helpers\Url::to("/ad/index") ?>> To Ads <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href=<?= \yii\helpers\Url::to("/cabinet/index") ?>> To My Ads <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="<?= \yii\helpers\Url::to(['user/security/logout'])?>" data-method="post"> Logout <span class="sr-only">(current)</span></a>
                    </li>
                <?php endif; ?>
                <li class="nav-item">
                    <a class="nav-link" href=<?= \yii\helpers\Url::to("/user/registration/register") ?>>Sign Up</a>
                </li>
            </ul>
            <span class="navbar-text">
    </span>
        </div>
    </nav>
 */

    NavBar::begin([
        'brandLabel' => 'App',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-dark bg-dark',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav mr-auto'],
        'items' => [
            ['label' => 'Главная', 'url' => ['/site/index'],  'visible' => !\Yii::$app->user->isGuest],
            // '<li style="padding-top: 8px">'.LanguageDropdown::widget().'</li>',
            ['label' => 'Login', 'url' => ['/user/auth/login'], 'visible' => Yii::$app->user->isGuest],
            ['label' => 'Sign Up', 'url' => ['/user/auth/signup'], 'visible' => Yii::$app->user->isGuest],
            [
                'label' => (!Yii::$app->user->isGuest) ? Yii::$app->user->identity->username : 'Гость',
                'template' => '<a href="{url}" ><i class="ti-user"></i> {label} <i class="fa fa-angle-down"></i></a>',
                'items' => [
                    ['label' => Yii::t('app','Список url'), 'url' => '/admin/index'],
                    ['label' => Yii::t('app', 'Выйти'), 'url' => ['/user/auth/logout'],
                     'linkOptions' => [
                         'data' => ['method' => 'post']
                     ],
                     //                        'template' => '<a href="{url}" data-method="post" data-params="'.Yii::$app->request->csrfParam.'='.Yii::$app->request->getCsrfToken().'"><i class="ti-lock"></i> {label}</a>',
                     'template' => '<a href="{url}" data-method="post"><i class="ti-lock"></i> {label}</a>',
                    ]
                ],
                'visible' => !Yii::$app->user->isGuest,
            ],
        ],
    ]);
    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0">
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer class="footer mt-auto py-3 text-muted">
    <div class="container">
        <p class="float-left">&copy; My Company <?= date('Y') ?></p>
        <p class="float-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>